// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXV4y8y3GPzTakNnFBkb3BItVBcPsIHEI',
    appId: '1:525057191871:web:3c7045a827c0732e0e3b0a',
    messagingSenderId: '525057191871',
    projectId: 'hahatalk-4c818',
    authDomain: 'hahatalk-4c818.firebaseapp.com',
    storageBucket: 'hahatalk-4c818.firebasestorage.app',
    measurementId: 'G-4T772P236M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIYJUbS31A7CID-iOCe2X45brNCN9b0HM',
    appId: '1:525057191871:android:a779021d9db8b0a70e3b0a',
    messagingSenderId: '525057191871',
    projectId: 'hahatalk-4c818',
    storageBucket: 'hahatalk-4c818.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqNy1psepFOVebBO1lVH49-OdF3MbmsxE',
    appId: '1:525057191871:ios:d17dc4f0cf4c5d820e3b0a',
    messagingSenderId: '525057191871',
    projectId: 'hahatalk-4c818',
    storageBucket: 'hahatalk-4c818.firebasestorage.app',
    iosBundleId: 'com.example.hahatalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqNy1psepFOVebBO1lVH49-OdF3MbmsxE',
    appId: '1:525057191871:ios:d17dc4f0cf4c5d820e3b0a',
    messagingSenderId: '525057191871',
    projectId: 'hahatalk-4c818',
    storageBucket: 'hahatalk-4c818.firebasestorage.app',
    iosBundleId: 'com.example.hahatalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXV4y8y3GPzTakNnFBkb3BItVBcPsIHEI',
    appId: '1:525057191871:web:5f3d36a1ab96df440e3b0a',
    messagingSenderId: '525057191871',
    projectId: 'hahatalk-4c818',
    authDomain: 'hahatalk-4c818.firebaseapp.com',
    storageBucket: 'hahatalk-4c818.firebasestorage.app',
    measurementId: 'G-4FRXQBTV61',
  );
}
